# Generated by Django 5.0 on 2024-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True, verbose_name='Телефон')),
                ('telegram_id', models.IntegerField(blank=True, null=True, verbose_name='Айди телеграм-профиля')),
                ('login_status', models.CharField(choices=[('waiting_qr_login', 'waiting'), ('error', 'error'), ('logined', 'logged'), ('logged_out', 'logged out')], default='waiting_qr_login', max_length=16, verbose_name='Cтатус аутентификации')),
                ('qr_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка для генерации QR-кода')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
